application: core-ed-debate
version: 6
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /style
  static_dir: style

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: main.py

